services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - kiruna-x
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/src/db:/app/src/db
    networks:
      - kiruna-x

networks:
  kiruna-x:
    driver: bridge