services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - kiruna-x
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    networks:
      - kiruna-x
  db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - kiruna-x
networks:
  kiruna-x:
    driver: bridge